exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'aangelaster@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'acrodriguez@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'addiazgr@uninorte.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'afalvarezri@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'agdelos@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'agenciajudicial@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'albamercedes.rojas@eiasa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'aldemarhh@yahoo.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'alejandra.figueroa@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'alejandro.martinez@fundacioncarvajal.org.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'alexander.ramirez@aliar.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'alexandra.solano@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'alfonsocadavid@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'amontealegre@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ana.erazo@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ana.florez@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'anajosefina.becerra@corficolombiana.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'anamurillo@italcol.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'andgaitan@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'andrea.camacho@esteesmibus.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'andres.rivera@cartonesamerica.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'andreshluna@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'andrespulga80@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'andrestobon00@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'anpedroza@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'anramirez@wfscorp.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'aocampo@cfa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'aosorio@funlam.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'arboledaripoll@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'arincon@nogales.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'asanchep@unab.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'asdabogados@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'aserna@envia.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'asesoresyconsultores@alvarovargasabogados.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'bayonaf@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'bbeltran@asercol.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'beatriz.agudelo@upb.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'biblioteca@lloredacamacho.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'biblioteca@uam.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'biblioteca@unicesar.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'biblioteca@unisinu.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'bibliougc@ugca.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'bibvir@uis.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'caeca64@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'caicedomunoz@cable.net.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cajaramillo@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'calidad@palmar.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'calopa.loaizapatio839@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'camartinez@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'carlosbarco@allabogados.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'carlosfernandez_abogado@yahoo.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'carlosg@mt.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'carlosmsg98@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'carolynnino@italcol.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ccastrillon@atesa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cdocumentacion@idu.gov.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cesaralfonsochavez@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'choyos@goh.law',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cjbuitragov@byblegal.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'clargo@cfa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'claudiahernandez@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cmourev@caracoltv.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'concentral@pelaezhermanos.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'consultores@orozcoasociados.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'contabilidad@ibustamante.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'contabilidad@sicre.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'controlerno@fonaviemcali.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'coordinacionhseq@ite.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cpaez@nutrion.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cpenuela@olimpica.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cuencaabundio@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cvalega@valegaabogados.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cvallejo@durespo.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'daniel.corrales.g@outlook.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'dannyce35@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'dbarrera@grasco.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'dcacuna@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'dcubillos@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ddolar1@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'dgamero@tecbaco.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'diana.gomez@unisabana.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'diana.iles@granamericasusme.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'diegoarsanchez@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'dileon@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'dilorsan@yahoo.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'dirbiblio@unab.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'direcciongestionhumana@habicicletas.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'dlegal@alfa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'dmarulanda@aguasdemanizales.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'doctorobles@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'duranmb@cable.net.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'duranyosorio@duranyosorio.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'eanino1@rbm.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'easabogado@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'eduardo.parrado@grupoexpress.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'edwinlopezfuentes@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'elugo@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'erfova@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'estefania.orrego@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'estjimenez@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'fbernate@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'fcarrillo_gutierrez@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'fcatacora@redcontable.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'fcujar@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'fegueri@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'fernandob@proenfar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'franalvarez@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'frhugave@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'fvelasquez@eraseo.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gdpadilla@rbm.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gebc68@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gerardoa.duque@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gerencia@colegiolacolina.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gerencia@morenovargas.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gerentefinanciero@eimpsa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'germangutierrez1961@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gestionhumana@codis.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gestionusc@tsicol.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gonzalezgallojuanguillermo@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gonzalodiazsoto@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'guerra172000@yahoo.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gulliver938@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'h.kingross@coopidrogas.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'hamidvega@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'heberthrios@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'hernan.olarte@fiscalia.gov.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'hildasabogal@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'hlancheros@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'hugo.diaz@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'hugo@xtg.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'hugomatamoros@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'hugoqb@outlook.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'hugosanin@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'igandini@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ignacio.conde@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'induvases@induvases.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'infraestructura@gafontibon.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ISABIB@ISA.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'j_fbf_@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jaimelancheros@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jcgs196240@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jcperezv@contraloriageneraldecaldas.gov.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jefededivisionjuridica@comfamiliarhuila.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jfseba@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jgalvez@incauca.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jgarciaosorio2@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jhsuarez@registraduria.gov.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jirincon@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jlgsabo@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jlopez@drummondltd.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jmartine@caracoltv.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jmoreno@grasco.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jmuriel@eraseo.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jocamargo@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'joctavioga@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'joesanar@yahoo.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jofegalindo@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jonh8j@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jorge.drada@fortoxsecurity.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jorge@carrizosaabogados.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jorgeorjuela2@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jovicent@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jpava@oal.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jpbuenog@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jpcm2001@yahoo.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jplozano@registraduria.gov.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jprietof@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juancarlos.prias@fipabogados.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juangcardonaiza@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'julio.rivera@fortoxsecurity.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'julio.villalba@electroequipos.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juliomogollon@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juridica@eiasa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juridica@ipuc.org.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juridica@jersalud.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juridica@uis.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juridico@correosanbartolo.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juridico@ismocol.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jurisnel@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'labernal@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lasernar@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'laurisbacca_15@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'leidy.reyes@vitalis.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lorena.rivera@jardinesdepaz.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ltrujillo@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lualbeba@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'luis.torres@consorcioexpress.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'luisfpabon@olcsal.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'luishguzmans@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'luiskmal@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lurubio@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lutamayo@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lvargas@superpolo.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lvelasco@unab.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lvilladiego@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'manlioandrs@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'maralbval@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'maria.manrique@rms-col.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'maria.mora@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'maria.vega@bancoagrario.gov.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mariapadilla@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'maribel.naranjo@bancoagrario.gov.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'martha.gomez@eiasa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'martinezabogados@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'martinezmalaver@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'martreyes@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mauricio.colmenares@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mauricio.vanegas@azulk.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mauricio.villegas@essilor.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mauriciojose80@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mbotero@olcsal.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mcifuentes@superpolo.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mgomez@casabritanica.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mgonzalez@uniminuto.edu',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'millang1494@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'millergaitan@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mllozadarodriguez@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mphernandez5@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mtorres@unicauca.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'munevarm@bancoavvillas.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'nabello@transelca.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'nancylg@colmedica.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'nbonilla@aicsas.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'nemesiocamelo@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ngonzalez@microplast.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ngonzalezs@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'nicolasmartinez@italcol.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'nicolawyer57@yahoo.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'njimenme@banrep.gov.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'nortega@labgothaplast.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'nsalazar@aguasdemanizales.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'obarrera@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'olgaalomia@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'oma1137@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'onietoca@banrep.gov.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'oscar.cardona@ua.la',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'paola.calderon@fortoxsecurity.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'paola.conde@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'paola.hernandez@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'paola_otero@yahoo.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'paolacortes@hecaduanas.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'parce@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'patrick.barros@consorcioexpress.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'paula.herrera@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'pedrogomez14@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'pedroivanbonilla@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'pfriasav@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'phr@phrlegal.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'possos912@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ppcg5@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'prgltda@yahoo.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'prohuila@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'raffo@raffopalauabogados.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ramo46@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'rdcarden@caracoltv.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'recursoshumanos@aviatur.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'recursoshumanos@bulevar.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'registro@ccm.org.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'rielvava@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ripamu@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'rmedina@drummondltd.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'roeliar@yahoo.es',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'rosalbatorres@flotalamacarena.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'rsarmiento@sarmientoabogados.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sabermudez@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sandra.ocampo@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sandra.rincon@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'santamaria2020@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sdiaz@elespectador.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'secretariageneral@urbaser.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sergio.ospina@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'servicios2biblioteca@unbosque.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sguerra@gane.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'silvia.diaz@yanbal.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'smabuchar@isa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sonia.morales@schott.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'tecnosur@tecnoquimicas.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'tesoreriaprodeho@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'urbano.soto@juanncorpas.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'vactib@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'valeria.orejuela@netafim.orbia.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'victormd35@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'vsandoval@wfscorp.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'wilcores@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'william.olaya@manuelita.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'wperez@cpc.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'yenifer.llano@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'yoxica@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'yurigarci@hotmail.com',	@Accion  = 1