
--**************************************************************
--*** CASO: ERROR AL CREAR EL FLUJO. MODIFICAR EL FLUJO. 
--**************************************************************
-- PRIMERO BUSCAMOS EL PROYECTO. 
SELECT * FROM proyecto p WHERE id_proyecto IN (3317448)
SELECT * FROM proyecto p where UPPER(p.nomproyecto) LIKE '%CIVIL%147-3317937%' ORDER BY 1 desc;


-- SEGUNDO BUSCAMOS LOS CAMBIOS DE LOS PARRAFOS Y LOS RESPALDAMOS COMO INSERT. 
SELECT * FROM CONTENIDOPARRAFOCAMBIO c WHERE CODPROYECTO = 3317448;

-- TERCERO VAMOS A OPTIMUS Y DETENEMOS EL FLUJO. 

-- CUARTO crear el nuevo flujo, y luego BUSCAMOS EL NUEVO PROYECTO. 
SELECT * FROM proyecto p where UPPER(p.nomproyecto) LIKE '%CIVIL%147-3317937%' ORDER BY 1 desc;

-- QUINTO HACEMOS EL UPDATE DE LOS PARRAFOS CON CAMBIOS . o EL INSERT SI LOS CAMBIOS OBTENIDOS EN EL PUNTO DOS NO ESTAN. 

-- tambien sirve para corregir envios. Ya que si no aparece es porque los cambios se quedaron en el proyecto anterior. 

UPDATE CONTENIDOPARRAFOCAMBIO SET CODPROYECTO =  3330525 WHERE CODPROYECTO = 3323693; 
UPDATE PROYECTO SET NOMPROYECTO = 'ESTATUTO GENERAL DE CONTRATACIÓN DE LA ADMINISTRACIÓN PÚBLICA Envío 56-3329201' WHERE ID_PROYECTO =3329201; 

-- SEXTO VERIFICAMOS LOS CAMBIOS. 
SELECT * FROM CONTENIDOPARRAFOCAMBIO c WHERE CODPROYECTO = 3329201;




-- CONSULTA PARA OBTENER LOS PARRAFOS DEL ENVIO. 
SELECT ID, FNOBTENERCONTEXTOPARRAFO( ID) AS CONTEXTO, ORDINAL , cp.xml 
FROM CONTENIDOPARRAFOCAMBIO CPC
iNNER JOIN CONTENIDOPARRAFO CP ON CP.ID= CPC. CODPARRAFO
wHERE CPC. FLAGPARRAFOEXCLUIDO=0 AND CPC. CODPROYECTO=3330525
AND (CP.FLAGNUEVO=1 OR CP.FLAGMODIFICADO=1 OR CP.FLAGBORRADO=1)
AND CP.IDANTERIOR <> 'NULL' AND CP.IDSIGUIENTE <> 'NULL'
ORDER BY ORDINAL ASC
