SELECT * FROM IMPORTDATA i
WHERE i.IDCONTENIDO = 'copnia';
 
 
DELETE FROM NORMACOMPLEMENTARIA
WHERE CODCONTENIDO = 'copnia'
AND CODARTICULOUBICACIONCOMP IN
(
    SELECT IDARTICULOUBICACION
    FROM NORMA_ARTICULOS_UBICACION
    INNER JOIN NORMA_ARTICULOS ON IDNORMA_ARTICULO = CODNORMAARTICULO
    WHERE CODCONTENIDO = 'copnia'
);
DELETE FROM NORMACOMPLEMENTARIA
WHERE CODCONTENIDO = 'copnia'
AND CODARTICULOUBICACIONPADRE IN
(
    SELECT IDARTICULOUBICACION
    FROM NORMA_ARTICULOS_UBICACION
    INNER JOIN NORMA_ARTICULOS ON IDNORMA_ARTICULO = CODNORMAARTICULO
    WHERE CODCONTENIDO = 'copnia'
);
 
 
DELETE FROM NORMA_ARTICULOS_RELACION nar
WHERE EXISTS(SELECT 1 FROM NORMA_UBICACION WHERE CODCONTENIDO = 'copnia' AND IDNORMAUBICACION = nar.IDNORMAUBICACION);
 
 
 
DELETE FROM NORMA_ARTICULOS_UBICACION nau
WHERE nau.CODCONTENIDO = 'copnia'
AND EXISTS(SELECT 1 FROM NORMA_ARTICULOS na WHERE na.IDNORMA_ARTICULO = nau.CODNORMAARTICULO);
 
 
 
DELETE FROM NORMA_UBICACION WHERE CODCONTENIDO = 'copnia' ;