---------------------------------------------------
--- ERROR: EL ARBOL SE QUEDA CARGANDO   &nbsp;
---------------------------------------------------
-- VER ARBOL

SELECT CP.ORDINAL ORDINALORG,
       CPA.ID CPAID,
       LEVEL AS NIVEL,CPA.DESCRIPCION, 
       LPAD(' ', (LEVEL - 1) * 2) ||
       TRIM(NVL(TO_CLOB(CPA.DESCRIPCION),
                REGEXP_REPLACE(CP.XML, '<[^>]*>', '')))
  FROM CONTENIDOPARRAFOARBOL CPA
 INNER JOIN CONTENIDOPARRAFO CP
    ON CPA.ID = CP.ID
   AND CPA.IDCONTENIDO = 'epsegsocia2009'
 START WITH CPA.IDPADRE = 'NULL'
CONNECT BY PRIOR CPA.ID = CPA.IDPADRE
 ORDER SIBLINGS BY CP.ORDINAL;

  -- CONTENIDO PARRAFO 

SELECT * FROM CONTENIDOPARRAFO
WHERE IDCONTENIDO IN ('eppenal2009') AND ID='xeppenal2009.9d9dff9320e27082b15b4ed7a086ba83'; 
  xeplaboral2009.fa5af87882a9494ea827ee83cd4b7e57
  
  
  © PÁGINA LEGAL
  
-- SE BUSCA EL NODO DEL ERROR 
SELECT * FROM CONTENIDOPARRAFOARBOL c
WHERE IDCONTENIDO = 'pconstitucional' AND id IN (
'xpconstitucional.c463b7c1799a301b457eedd5c18af326'
,'xpconstitucional.9d9dff9320e27082b15b4ed7a086ba83'
,'xpconstitucional.f7c19a2db7da7f032c2ef0f967a5d54c'
)



-- UPDATE DEL ARBOL. EL PARRAFO TIENE UNA ETIQUETA --<br>
UPDATE  CONTENIDOPARRAFOARBOL c SET DESCRIPCION = REPLACE(descripcion, '</negrita>', '') WHERE IDCONTENIDO ='eppenal2009';  
UPDATE  CONTENIDOPARRAFOARBOL c SET DESCRIPCION = REPLACE(descripcion, '&nbsp;', '') WHERE IDCONTENIDO ='eplaboral2009';