ALTER SESSION SET CURRENT_SCHEMA = "SPCUSER";

SELECT * FROM clasificacioncontenido
WHERE codclasificacioncontenido = 8;

insert into CLASIFICACIONCONTENIDO (IDCLASIFICACIONCONTENIDO, NOMCLASIFICACIONCONTENIDO, CODCLASIFICACIONCONTENIDO, ESPUBLICACION)
values (1430, 'Pauta Legal', 8, 0);




