-- VARIABLES 

select * from VARIABLEVALOR order by IDVARIABLEVALOR desc;

--1	PORCENTAJE_AJUSTE_COSTO
select * from VARIABLEVALOR WHERE IDVARIABLE = 1 order by IDVARIABLEVALOR desc;
--2	AÑO
select * from VARIABLEVALOR WHERE IDVARIABLE = 2 order by IDVARIABLEVALOR desc;
--3	IPC
select * from VARIABLEVALOR WHERE IDVARIABLE = 3 order by IDVARIABLEVALOR desc;
--4	UVT
select * from VARIABLEVALOR WHERE IDVARIABLE = 4 order by IDVARIABLEVALOR desc;
--5	RESOLUCION_DIAN
select * from VARIABLEVALOR WHERE IDVARIABLE = 5 order by IDVARIABLEVALOR desc;
--6	SMLMV
select * from VARIABLEVALOR WHERE IDVARIABLE = 6 order by IDVARIABLEVALOR desc;
--41 UVB
select * from VARIABLEVALOR WHERE IDVARIABLE = 41 order by IDVARIABLEVALOR desc;


INSERT INTO VARIABLEVALOR (IDVARIABLE,VALOR,FECHAINICIO,VERSION,VALORTEXTO,ETIQUETA) VALUES (1,'4','01/01/27',null,null,2027);    -- 1	PORCENTAJE_AJUSTE_COSTO
INSERT INTO VARIABLEVALOR (IDVARIABLE,VALOR,FECHAINICIO,VERSION,VALORTEXTO,ETIQUETA) VALUES (2,'2027','01/01/27',null,null,2027); -- 2	AÑO
INSERT INTO VARIABLEVALOR (IDVARIABLE,VALOR,FECHAINICIO,VERSION,VALORTEXTO,ETIQUETA) VALUES (3,'3,17','01/01/27',null,null,2027); --3	IPC
INSERT INTO VARIABLEVALOR (IDVARIABLE,VALOR,FECHAINICIO,VERSION,VALORTEXTO,ETIQUETA) VALUES (4,'47065','01/01/27',null,null,2027); --4	UVT
INSERT INTO VARIABLEVALOR (IDVARIABLE,VALOR,FECHAINICIO,VERSION,VALORTEXTO,ETIQUETA) VALUES (5,null,'01/01/27',null,'DIAN, Res. 187, nov. 28/2023',2027); --5	RESOLUCION_DIAN
INSERT INTO VARIABLEVALOR (IDVARIABLE,VALOR,FECHAINICIO,VERSION,VALORTEXTO,ETIQUETA) VALUES (6,'1160000','01/01/27',null,null,2027); --6	SMLMV
INSERT INTO VARIABLEVALOR (IDVARIABLE,VALOR,FECHAINICIO,VERSION,VALORTEXTO,ETIQUETA) VALUES (41,'10000','01/01/27',null,null,2027); --41 UVB


-- update para corregir algun dato. 
update VARIABLEVALOR set VALOR = '1750905' where IDVARIABLEVALOR = 608 and ETIQUETA = 2026;
