--**************************************************************
--*** caso atributo NO encontrado 
--**************************************************************

      SELECT IDATRIBUTO, NOMATRIBUTO  FROM
        (
        SELECT DISTINCT ATR.IDATRIBUTO, ATR.NOMATRIBUTO
        FROM       ATRIBUTO ATR
        INNER JOIN ATRIBUTOCLASIFICACIONCONTENIDO ACC ON ACC.CODATRIBUTO = ATR.IDATRIBUTO
        WHERE ACC.IDCONTENIDO = 'civilba'
        AND 	ATR.FLAGBORRADO = 0
        OR    (ACC.IDCONTENIDO IS NULL AND ACC.CODCLASIFICACIONCONTENIDO IS NULL)
        OR    ACC.CODCLASIFICACIONCONTENIDO IN (
        SELECT IDCLASIFICACIONCONTENIDO
        FROM CLASIFICACIONCONTENIDO
        START WITH IDCLASIFICACIONCONTENIDO = (SELECT CODTIPOCONTENIDO FROM CONTENIDO WHERE IDCONTENIDO = 'civilba')
        CONNECT BY PRIOR CODCLASIFICACIONCONTENIDO = IDCLASIFICACIONCONTENIDO)
        )ORDER BY NOMATRIBUTO


-- verificar arbol de atributos 
        SELECT CP.ID, TRIM(REGEXP_REPLACE(CP.XML, '<[^<>]*>', '')) TEXTO,     
        TO_NUMBER(REGEXP_REPLACE(A.NOMATRIBUTO, '\D+')) NIVEL, 
		CP.IDCONTENIDO, CP.FLAGBORRADO,
       LPAD(' ', (TO_NUMBER(REGEXP_REPLACE(A.NOMATRIBUTO, '\D+')) - 1) * 2) ||
       TRIM(NVL(TO_CLOB(REGEXP_REPLACE(CP.XML, '<[^>]*>', '')),
                REGEXP_REPLACE(CP.XML, '<[^>]*>', '')))
              FROM CONTENIDOPARRAFO CP
              INNER JOIN ATRIBUTOPARRAFO AP ON AP.CODPARRAFO = CP.ID
              INNER JOIN ATRIBUTO A ON A.IDATRIBUTO = AP.CODATRIBUTO
              WHERE AP.CODATRIBUTO IN (953,954,972,980, 17) AND CP.IDCONTENIDO = 'civilba'        
        ORDER BY CP.ORDINAL



SELECT * FROM ATRIBUTO a WHERE idatributo IN ( 953,954,972,980, 17)


SELECT * FROM ATRIBUTOPARRAFO a  WHERE CODPARRAFO IN ('xcivilba.1d367b6c55e5492da08f0f98e679484e', 'xcivilba.95d201005b29413e9eb3d5da33ade445'
 ,'xcivilba.0c16833d14814aa3b6f8ac3a4dd5494f', 'xcivilba.7e331b2917b349f2a52cb593d41b4056','xcivilba.dfafcefa169646379ddef64c444d71fd')

SELECT * FROM contenidoparrafo WHERE id IN ('xcivilba.1d367b6c55e5492da08f0f98e679484e'
 ,'xcivilba.0c16833d14814aa3b6f8ac3a4dd5494f', 'xcivilba.7e331b2917b349f2a52cb593d41b4056','xcivilba.dfafcefa169646379ddef64c444d71fd')

-- ACTUALIZAR REGISTRO 
UPDATE atributoparrafo SET CODATRIBUTO = 953 WHERE codparrafo='xcomercio.b9c475b919da4bcbb9e0a7e694129428'; 


-- CUANDO EN EL ARBOL DE NORMA NO APARECE UN ARTICULO ES PORQUE LE HACE FALTA EL ATRIBUTOPARRAFO. 
INSERT INTO ATRIBUTOPARRAFO (80048808, 953, 'xestatuto.6ba51991885b49509ce83c90995a7e33'); 




SELECT * FROM ATRIBUTOCLASIFICACIONCONTENIDO a WHERE IDCONTENIDO = 'civilbasico2025a'  --955

-----INSERT INTO ATRIBUTOCLASIFICACIONCONTENIDO (codatributo, CODCLASIFICACIONCONTENIDO, IDCONTENIDO) VALUES (955, NULL, 'estatuto')














SELECT * FROM ATRIBUTOPARRAFORELACION a  WHERE IDATRIBUTOPARRAFOREL  =79967290
SELECT * FROM  CLASIFICACIONCONTENIDO
SELECT * FROM  ATRIBUTOCLASIFICACIONCONTENIDO WHERE CODATRIBUTO IN (         816,   824, 17,  828,   357,16)







        