-- buscar el parrafo 

SELECT * FROM NORMA_UBICACION nu WHERE CODPARRAFO ='xcivil.a5fa372260a647129152c28ef3d29c68'
SELECT * FROM NORMA_ARTICULOS_RELACION WHERE IDNORMAUBICACION = 455001

SELECT 
    NAR.IDNORMAUBICACION,
    NAR.IDARTICULOUBICACION,
    NAU.CODCONTENIDO,
    NAU.PRINCIPAL, NAU.*,
    NC.CODARTICULOUBICACIONPADRE,
    NC.CODARTICULOUBICACIONCOMP
FROM NORMA_ARTICULOS_RELACION NAR
INNER JOIN NORMA_ARTICULOS_UBICACION NAU
    ON NAU.IDARTICULOUBICACION = NAR.IDARTICULOUBICACION
INNER JOIN NORMACOMPLEMENTARIA NC
    ON NC.CODARTICULOUBICACIONPADRE = NAU.IDARTICULOUBICACION
    OR NC.CODARTICULOUBICACIONCOMP = NAU.IDARTICULOUBICACION
WHERE NAR.IDNORMAUBICACION = 455001;

-- VALIDAR QUE SOLO ESTA EN CODARTICULOUBICACIONCOMP
SELECT *
FROM NORMACOMPLEMENTARIA
WHERE CODARTICULOUBICACIONPADRE IN (1059265,1059270)
   OR CODARTICULOUBICACIONCOMP IN (1059265,1059270)		

----  update  NORMA_ARTICULOS_UBICACION SET PRINCIPAL = 0 WHERE IDARTICULOUBICACION IN  (1059265,1059270);

   
   
   
   --- otras consultas que pueden servir en algun momento. 



SELECT na.*, NAU.*
											FROM NORMACOMPLEMENTARIA NC
										 INNER JOIN NORMA_ARTICULOS_UBICACION NAU
												ON NC.CODARTICULOUBICACIONCOMP =
													 NAU.IDARTICULOUBICACION
													 INNER JOIN NORMA_ARTICULOS na ON NA.IDNORMA_ARTICULO = NAU.CODNORMAARTICULO 
										 INNER JOIN NORMA_ARTICULOS_RELACION NAR
												ON NAU.IDARTICULOUBICACION = NAR.IDARTICULOUBICACION
										 WHERE NAR.IDNORMAUBICACION  = 455001
										 
				 
										 
										 



SELECT NAR.IDNORMAUBICACION
											FROM NORMACOMPLEMENTARIA NC
										 INNER JOIN NORMA_ARTICULOS_UBICACION NAU
												ON NC.CODARTICULOUBICACIONCOMP =
													 NAU.IDARTICULOUBICACION
										 INNER JOIN NORMA_ARTICULOS_RELACION NAR
												ON NAU.IDARTICULOUBICACION = NAR.IDARTICULOUBICACION
										 WHERE NC.CODARTICULOUBICACIONPADRE = ARTICULOUBICACION
										 GROUP BY NAR.IDNORMAUBICACION




										 
										 
										 

										 
										 
									
SELECT * FROM NORMA_ARTICULOS na WHERE na.CODNORMA  = 119992; 

SELECT * FROM NORMA_ARTICULOS_UBICACION nau WHERE nau.CODNORMAARTICULO  IN (622486) AND CODCONTENIDO  = 'protribu'; 

SELECT * FROM NORMA_ARTICULOS_RELACION nar WHERE nar.IDARTICULOUBICACION IN (1623382);

SELECT * FROM SPCUSER.NORMACOMPLEMENTARIA WHERE CODARTICULOUBICACIONCOMP  IN (1623382);

SELECT * FROM NORMACOMPLEMENTARIA n WHERE id IN (222004) AND CODCONTENIDO = 'protribu'; 





		
SELECT NAR.IDNORMAUBICACION
											FROM NORMACOMPLEMENTARIA NC
										 INNER JOIN NORMA_ARTICULOS_UBICACION NAU
												ON NC.CODARTICULOUBICACIONCOMP =
													 NAU.IDARTICULOUBICACION
										 INNER JOIN NORMA_ARTICULOS_RELACION NAR
												ON NAU.IDARTICULOUBICACION = NAR.IDARTICULOUBICACION
										 WHERE NAU.CODNORMAARTICULO  = 422268
										 
										 
SELECT *
											FROM NORMACOMPLEMENTARIA NC
										 INNER JOIN NORMA_ARTICULOS_UBICACION NAU
												ON NC.CODARTICULOUBICACIONCOMP =
													 NAU.IDARTICULOUBICACION
										 INNER JOIN NORMA_ARTICULOS_RELACION NAR
												ON NAU.IDARTICULOUBICACION = NAR.IDARTICULOUBICACION
										 WHERE NC.CODARTICULOUBICACIONPADRE = 119992										 
										 



	