-- =========================
-- CONSULTAR DATOS. 
-- =========================
--OBRAS PROCESADAS
--'regaduanas', 'REFORMALABORAL', 'rie', '6d97fe0216e58002e0430a0101518002' -- arancel colombia
-- PASO 2 VALIDAR 
-- contenidoflujo. DEBE ESTAR EN 1 FLAGFLUJOACTIVO, Y TENER CODPROYECTO. 

-- PASO 3 ELIMINAR LOS REGISTROS DE ESTAS TABLAS. SP_CORTE_LIMPIARCAMBIOS
-- CONTENIDOCONTROLCAMBIOS
-- CONTENIDOPARRAFOCAMBIO

-- PRIMERO 

SELECT IDCONTENIDO, FLAGCONTROLCAMBIOS, FLAGSOPORTAENVIO 
 FROM CONTENIDO c  WHERE IDCONTENIDO = 'eptributario2009'; 
 
 
update contenido set  FLAGCONTROLCAMBIOS = 0, FLAGSOPORTAENVIO = 0 
WHERE IDCONTENIDO  =  'eptributario2009'; 

-- SEGUNDO 
-- DEBE ESTAR EN FLAGFLUJOACTIVO = 1, CODPROYECTO DEBE ESTAR LLENO CON EL ULTIMO PROYECTO ACTIVO.
SELECT CODCONTENIDO , FLAGFLUJOACTIVO, CODPROYECTO  FROM contenidoflujo



SELECT * FROM contenidoparrafo WHERE IDCONTENIDO = 'eptributario2009' AND FLAGBORRADO !=0

-- TERCERO 


SELECT DISTINCT C.IDCONTENIDO, C.NOMCONTENIDO, P.ID_PROYECTO, P.CODUSUARIO 
FROM CONTENIDO C INNER JOIN PROYECTO P ON C.IDCONTENIDO= P.CODEXTERNOTEXTO 
ORDER BY C.IDCONTENIDO, P.ID_PROYECTO DESC




DECLARE
    V_SALIDA VARCHAR2(4000);
BEGIN
    PERUUSER.SP_CORTE_LIMPIARCAMBIOS(
        'eptributario2009',
        '84',
        '9',
        V_SALIDA
    );

    DBMS_OUTPUT.PUT_LINE('Salida: ' || V_SALIDA);
END;



-- =========================
-- PARAMETROS (AJUSTAR)
-- =========================

DECLARE
    P_IDCONTENIDO VARCHAR2(50) := 'pruebas';
    P_CODPROYECTO VARCHAR2(50) := '22';
    P_COUSUARIO   VARCHAR2(50) := '29';
BEGIN

	-- =========================
	-- INICIO
	-- =========================

	-- Limpieza CONTENIDOPARRAFO
	UPDATE CONTENIDOPARRAFO
	SET XML = REGEXP_REPLACE(XML,
	'(<\?xm-insertion_mark_start\s.*?\?>)|(<\?xm-insertion_mark_end\s*\?>)|(<\?xm-deletion_mark\s.*?\?>)',
	'', 1, 0, 'n')
	WHERE REGEXP_LIKE(XML,
	'(<\?xm-insertion_mark_start\s.*?\?>)|(<\?xm-deletion_mark\s.*?\?>)', 'n')
	AND ID IN (
		SELECT ID
		FROM CONTENIDOPARRAFOCAMBIO CPC
		INNER JOIN CONTENIDOPARRAFO CP ON CP.ID = CPC.CODPARRAFO
		WHERE CPC.CODPROYECTO = P_CODPROYECTO
		AND (CP.FLAGNUEVO = 1 OR CP.FLAGMODIFICADO = 1)
	);

	-- Limpieza CONTENIDOPARRAFOTABLA
	UPDATE CONTENIDOPARRAFOTABLA
	SET XML = REGEXP_REPLACE(XML,
	'(<\?xm-insertion_mark_start\s.*?\?>)|(<\?xm-insertion_mark_end\s*\?>)|(<\?xm-deletion_mark\s.*?\?>)', '')
	WHERE REGEXP_LIKE(XML,
	'(<\?xm-insertion_mark_start\s.*?\?>)|(<\?xm-deletion_mark\s.*?\?>)')
	AND IDPARRAFO IN (
		SELECT ID
		FROM CONTENIDOPARRAFOCAMBIO CPC
		INNER JOIN CONTENIDOPARRAFO CP ON CP.ID = CPC.CODPARRAFO
		WHERE CPC.CODPROYECTO = P_CODPROYECTO
		AND (CP.FLAGNUEVO = 1 OR CP.FLAGMODIFICADO = 1)
	);

	-- Delete tabla
	DELETE FROM CONTENIDOPARRAFOTABLA
	WHERE IDPARRAFO IN (
		SELECT ID
		FROM CONTENIDOPARRAFOCAMBIO CPC
		INNER JOIN CONTENIDOPARRAFO CP ON CP.ID = CPC.CODPARRAFO
		WHERE CPC.CODPROYECTO = P_CODPROYECTO
		AND (CP.FLAGNUEVO = 1 OR CP.FLAGMODIFICADO = 1 OR CP.FLAGBORRADO IN (1,2))
	);

	-- Reset flags
	UPDATE CONTENIDOPARRAFO CP
	SET CP.FLAGNUEVO = 0,
		CP.FLAGMODIFICADO = 0
	WHERE CP.IDCONTENIDO = P_IDCONTENIDO
	AND EXISTS (
		SELECT 1
		FROM CONTENIDOPARRAFOCAMBIO CPC
		WHERE CP.ID = CPC.CODPARRAFO
		AND CPC.CODPROYECTO = P_CODPROYECTO
		AND NOT EXISTS (
			SELECT 1
			FROM CONTENIDOPARRAFOCAMBIO CPC1
			WHERE CPC1.CODPARRAFO = CPC.CODPARRAFO
			AND CPC1.CODPROYECTO <> P_CODPROYECTO
		)
	)
	AND (CP.FLAGNUEVO = 1 OR CP.FLAGMODIFICADO = 1);

	-- Reemplazo del cursor (simplificado)
	UPDATE CONTENIDOPARRAFO CP
	SET XML = REGEXP_REPLACE(
		XML,
		'<Concordancias id = \"' ||
		(
			SELECT CGC.ID
			FROM CONTENIDOGRUPOCONCORDANCIA CGC
			INNER JOIN CONTENIDOPARRAFOCAMBIO CPC
				ON CGC.IDPARRAFO = CPC.CODPARRAFO
			WHERE CPC.CODPROYECTO = P_CODPROYECTO
			AND CGC.FLAGBORRADO = 1
			AND CGC.IDPARRAFO = CP.ID
			FETCH FIRST 1 ROWS ONLY
		)
		|| '\" class = \"nostyle\"> </Concordancias>',
		''
	)
	WHERE EXISTS (
		SELECT 1
		FROM CONTENIDOGRUPOCONCORDANCIA CGC
		INNER JOIN CONTENIDOPARRAFOCAMBIO CPC
			ON CGC.IDPARRAFO = CPC.CODPARRAFO
		WHERE CPC.CODPROYECTO = P_CODPROYECTO
		AND CGC.FLAGBORRADO = 1
		AND CP.ID = CGC.IDPARRAFO
	);

	-- Deletes concordancias
	DELETE FROM CONTENIDOCONCORDANCIA
	WHERE ID IN (
		SELECT CC.ID
		FROM CONTENIDOPARRAFOCAMBIO CPC
		INNER JOIN CONTENIDOGRUPOCONCORDANCIA CGC
			ON CGC.IDPARRAFO = CPC.CODPARRAFO
		INNER JOIN CONTENIDOCONCORDANCIA CC
			ON CC.IDGRUPOCONCORDANCIA = CGC.ID
		WHERE CPC.CODPROYECTO = P_CODPROYECTO
		AND CC.FLAGBORRADO = 1
	);

	DELETE FROM CONTENIDOGRUPOCONCORDANCIA
	WHERE ID IN (
		SELECT CGC.ID
		FROM CONTENIDOPARRAFOCAMBIO CPC
		INNER JOIN CONTENIDOGRUPOCONCORDANCIA CGC
			ON CGC.IDPARRAFO = CPC.CODPARRAFO
		WHERE CPC.CODPROYECTO = P_CODPROYECTO
		AND CGC.FLAGBORRADO = 1
	);

	-- Update flagsistema
	UPDATE CONTENIDOPARRAFO
	SET FLAGSISTEMA = 0
	WHERE ID IN (
		SELECT ID
		FROM CONTENIDOPARRAFO
		WHERE IDCONTENIDO = P_IDCONTENIDO
		AND FLAGSISTEMA = 1
		AND FLAGBORRADO IN (1,2)
		AND IDANTERIOR <> 'NULL'
		AND IDSIGUIENTE <> 'NULL'
	);

	--Se eliminan los parrafos borrados en el proyecto actual, y su respectivo historial
	spEliminarParrafosBorrados(P_IDCONTENIDO, P_CODPROYECTO, P_COUSUARIO);
  
	-- Limpieza auditoría
	UPDATE CONTENIDOPARRAFO
	SET FECHAACTUALIZACION = NULL,
		CODUSUARIOCAMBIO = NULL
	WHERE ID IN (
		SELECT CODPARRAFO
		FROM CONTENIDOPARRAFOCAMBIO
		WHERE CODPROYECTO = P_CODPROYECTO
	);

	-- Delete cambios
	DELETE FROM CONTENIDOPARRAFOCAMBIO
	WHERE CODPROYECTO = P_CODPROYECTO;

	-- Delete control cambios
	DELETE FROM CONTENIDOCONTROLCAMBIOS
	WHERE IDCONTENIDO = P_IDCONTENIDO
	AND FLAGBORRADO <> 0;

	-- Update QR
	UPDATE CONTENIDOPARRAFOQR
	SET FLAGENVIO = 0
	WHERE CODCONTENIDO = P_IDCONTENIDO;

  --Se guarda el registro del corte en la tabla Contenido corte
  spGuardarDatosCorte(P_IDCONTENIDO, P_CODPROYECTO, P_COUSUARIO);
  
	-- =========================
	-- FIN (CONFIRMAR CAMBIOS)
	-- =========================
	COMMIT;


END; 
