SELECT E.COD_PARRAFO, cp.*,  CD.COD_PARRAFO, cd.descripcion  
FROM 

contenidoparrafo cp INNER JOIN 

ENLACES E ON cp.id = e.cod_parrafo 
INNER JOIN CONTENIDODESTINOS CD 
ON CD.ID_DESTINO  = E.COD_DESTINO 
AND CD.COD_CONTENIDO = 'doctriaduanas'
WHERE E.COD_CONTENIDO = 'regaduanas';



SELECT E.COD_CONTENIDO, CD.COD_CONTENIDO, cd.descripcion  
FROM 


ENLACES E 
INNER JOIN CONTENIDODESTINOS CD 
ON CD.ID_DESTINO  = E.COD_DESTINO 
AND CD.COD_CONTENIDO = 'doctriaduanas'
WHERE E.COD_CONTENIDO = 'regaduanas';