/*CREATE OR REPLACE PROCEDURE SPCUSER.SP_DEL_NORMAARTICULO_CASCADA(REFCONTENT        IN VARCHAR2,
																												 NORMAUBICACION    IN NUMBER,
																												 ARTICULOUBICACION IN NUMBER) IS --1623390
	REFTIPO NUMBER;
BEGIN*/
	IF ARTICULOUBICACION IS NULL THEN
	
		FOR ARTICULO IN (SELECT IDARTICULOUBICACION
											 FROM NORMA_ARTICULOS_RELACION
											WHERE IDNORMAUBICACION = NORMAUBICACION) LOOP
			SP_DEL_NORMAARTICULO_CASCADA(REFCONTENT, NULL, ARTICULO.IDARTICULOUBICACION);
		END LOOP;
	
		DELETE FROM NORMA_UBICACION
		 WHERE IDNORMAUBICACION = NORMAUBICACION
			 AND CODCONTENIDO = REFCONTENT;
	
	ELSE
	
		SELECT PRINCIPAL
			INTO REFTIPO
			FROM NORMA_ARTICULOS_UBICACION
		 WHERE IDARTICULOUBICACION = ARTICULOUBICACION;
	
		IF REFTIPO = 1 THEN
			-- Si es un artículo principal
			FOR NORMA IN (SELECT NAR.IDNORMAUBICACION
											FROM NORMACOMPLEMENTARIA NC
										 INNER JOIN NORMA_ARTICULOS_UBICACION NAU
												ON NC.CODARTICULOUBICACIONCOMP =
													 NAU.IDARTICULOUBICACION
										 INNER JOIN NORMA_ARTICULOS_RELACION NAR
												ON NAU.IDARTICULOUBICACION = NAR.IDARTICULOUBICACION
										 WHERE NC.CODARTICULOUBICACIONPADRE = ARTICULOUBICACION
										 GROUP BY NAR.IDNORMAUBICACION) LOOP
				SP_DEL_NORMAARTICULO_CASCADA(REFCONTENT, NORMA.IDNORMAUBICACION, NULL);
			END LOOP;
		ELSE
			-- Si es un artículo complementario
			DELETE FROM NORMACOMPLEMENTARIA
			 WHERE CODARTICULOUBICACIONCOMP = ARTICULOUBICACION
				 AND CODCONTENIDO = REFCONTENT;
		
		END IF;
	
		DELETE FROM NORMA_ARTICULOS_RELACION
		 WHERE IDARTICULOUBICACION = ARTICULOUBICACION;
	
		DELETE FROM NORMA_ARTICULOS_UBICACION
		 WHERE IDARTICULOUBICACION = ARTICULOUBICACION
			 AND CODCONTENIDO = REFCONTENT;
	END IF;
END;

				update 
		 NORMA_ARTICULOS_UBICACION set principal = 0
		 WHERE IDARTICULOUBICACION IN (1469042); 