SELECT * FROM aliasobra WHERE ALIAS LIKE '%contebasico2025a%' 
SELECT * FROM contenido WHERE idcontenido LIKE '%contebasico2025a%'
SELECT * FROM contenidotransformador WHERE codcontenido LIKE '%contebasico2025a%' 


-----------------estatuto2025-----------------
insert into aliasobra (ALIAS, DESCRIPCION, DISPONIBLE)
values ('estatuto2025', 'ESTATUTO TRIBUTARIO 32A ED', 1);

insert into contenidotransformador (CODCONTENIDO, CODTRANSFORMADOR, EJECUTAR, FECHAULTIMAEJECUCION, CONFIGURACION, CODCONTEXTO, COUNTTRANSFORMACIONES, FECHAPROXIMAEJECUCION, PERIODICIDAD, PORSECCIONPOSIBLE, EJECUTAR_REINCORPORACION, SECCION)
values ('estatuto2025', 60, 'N', SYSDATE, '<root><parametros> <entry name="ALIAS">estatuto2025</entry> <entry name="VISTA_APPMOVIL">S</entry> <entry name="INDICESINCLUIR">FALSE</entry> <entry name="TITULO"></entry> <entry name="CLASIFICACION">ESPECIALIZADA</entry><entry name="NORMAS_ARTICULOS">CRONOLOGICO</entry> </parametros></root>', 44, 10, null, null, 1, 'N', 0);


insert into contenido (IDCONTENIDO, NOMCONTENIDO, FECHACREACION, CODUSUARIO, CODTIPOCONTENIDO, FLAGBORRADO, FLAGCONTROLCAMBIOS, FLAGCODIGOSINTERNOS, FLAGBLOQUEOSISTEMA, FLAGRESINCORDINAL, CODFICHA, CODPARRAFOINICIAL, FECHACORTE, VERSION, FECHADISPONIBILIDAD, FLAGREINDEXAR, FLAGREAGRUPAR, FECHAACTUALIZACION, FLAGSOPORTAENVIO, IDTEMP, VIGENCIA, CANTIDADPARRAFOS, FLAGMARCAR, PRIORIDADMARCADO, TIPORESERVA)
values ('estatuto2025', 'ESTATUTO TRIBUTARIO 32A ED', SYSDATE, 8963, 845, 0, 1, 0, 0, 0, 0, 0, SYSDATE, 0, SYSDATE - 1, 0, 1, SYSDATE, 1, 2528053, 1, 0, null, null, null);







SELECT * from  CONTENIDO WHERE IDCONTENIDO = 'sijrmineral'; 
SELECT * from  CONTENIDOTRANSFORMADOR c WHERE CODCONTENIDO = 'sijcomercio'; 

SELECT * from  CONTENIDOCONTROLCAMBIOS WHERE IDCONTENIDO = 'sijrmineral'; 

SELECT * FROM IMPORTDATA i   WHERE IDCONTENIDO = 'sijrmineral'; 









INSERT INTO CONTENIDOTRANSFORMADOR (CODCONTENIDO,CODTRANSFORMADOR,EJECUTAR,FECHAULTIMAEJECUCION,CONFIGURACION,CODCONTEXTO,COUNTTRANSFORMACIONES,FECHAPROXIMAEJECUCION,PERIODICIDAD,PORSECCIONPOSIBLE,EJECUTAR_REINCORPORACION,SECCION,SERVICIO,EJECUTAR_EXP) VALUES
	 ('sijrmineral',1,'N',NULL,'<root>
  <parametros>
    <entry name="PARRAFO_INICIO">2C7AEFB4AEC7017CE0630A010182BF89</entry>
  </parametros>
</root>',3,0,NULL,NULL,1,'S',0,2,'N'); 

INSERT INTO CONTENIDOTRANSFORMADOR (CODCONTENIDO,CODTRANSFORMADOR,EJECUTAR,FECHAULTIMAEJECUCION,CONFIGURACION,CODCONTEXTO,COUNTTRANSFORMACIONES,FECHAPROXIMAEJECUCION,PERIODICIDAD,PORSECCIONPOSIBLE,EJECUTAR_REINCORPORACION,SECCION,SERVICIO,EJECUTAR_EXP) VALUES
 ('sijrmineral',2,'N',NULL,NULL,3,0,NULL,NULL,1,'S',0,2,'N'); 
	 

INSERT INTO CONTENIDOTRANSFORMADOR (CODCONTENIDO,CODTRANSFORMADOR,EJECUTAR,FECHAULTIMAEJECUCION,CONFIGURACION,CODCONTEXTO,COUNTTRANSFORMACIONES,FECHAPROXIMAEJECUCION,PERIODICIDAD,PORSECCIONPOSIBLE,EJECUTAR_REINCORPORACION,SECCION,SERVICIO,EJECUTAR_EXP) VALUES	 
	 ('sijrmineral',4,'N',NULL,'<root>
  <parametros>
    <entry name="PARRAFO_INICIO">2C7AEFB4AEC7017CE0630A010182BF89</entry>
  </parametros>
</root>',3,0,NULL,NULL,1,'S',0,2,'N'); 


INSERT INTO CONTENIDOTRANSFORMADOR (CODCONTENIDO,CODTRANSFORMADOR,EJECUTAR,FECHAULTIMAEJECUCION,CONFIGURACION,CODCONTEXTO,COUNTTRANSFORMACIONES,FECHAPROXIMAEJECUCION,PERIODICIDAD,PORSECCIONPOSIBLE,EJECUTAR_REINCORPORACION,SECCION,SERVICIO,EJECUTAR_EXP) VALUES
	 ('sijrmineral',11,'N',NULL,NULL,3,0,NULL,NULL,1,'S',0,2,'N'); 


INSERT INTO CONTENIDOTRANSFORMADOR (CODCONTENIDO,CODTRANSFORMADOR,EJECUTAR,FECHAULTIMAEJECUCION,CONFIGURACION,CODCONTEXTO,COUNTTRANSFORMACIONES,FECHAPROXIMAEJECUCION,PERIODICIDAD,PORSECCIONPOSIBLE,EJECUTAR_REINCORPORACION,SECCION,SERVICIO,EJECUTAR_EXP) VALUES
	 ('sijrmineral',30,'N',TIMESTAMP'2025-01-20 16:15:45.0','<root>
  <parametros>
    <entry name="ALIAS">sijrmineral</entry>
    <entry name="VISTA_APPMOVIL">S</entry> 
    <entry name="INDICESINCLUIR">FALSE</entry>
	<entry name="PARRAFO_INICIO">2C7AEFB4AEC7017CE0630A010182BF89</entry>
  </parametros>
</root>',3,6,NULL,NULL,1,'N',NULL,1,'N'); 


INSERT INTO CONTENIDOTRANSFORMADOR (CODCONTENIDO,CODTRANSFORMADOR,EJECUTAR,FECHAULTIMAEJECUCION,CONFIGURACION,CODCONTEXTO,COUNTTRANSFORMACIONES,FECHAPROXIMAEJECUCION,PERIODICIDAD,PORSECCIONPOSIBLE,EJECUTAR_REINCORPORACION,SECCION,SERVICIO,EJECUTAR_EXP) VALUES
	 ('sijrmineral',60,'N',TIMESTAMP'2024-08-23 15:38:05.0','<root>
  <parametros>
    <entry name="ALIAS">sijrmineral</entry>
    <entry name="VISTA_APPMOVIL">S</entry> 
    <entry name="INDICESINCLUIR">FALSE</entry>
	<entry name="PARRAFO_INICIO">2C7AEFB4AEC7017CE0630A010182BF89</entry>
  </parametros>
</root>',3,1,NULL,NULL,1,'N',NULL,1,'N');