exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'vilmavillaperez@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lgiraldo@agsamericas.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'daniel.medina@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'amayaabogados@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'alejandra.figueroa@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'maria.mora@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sergio.ospina@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lily.vergara@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mauricio.colmenares@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'josemiguel.garcia@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'bertath.molano@libertadores.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'hugo.diaz@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'carolina.osorio@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'alexandra.solano@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'fvelasquez@interaseo.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mariadelmar.gonzal@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'paola.conde@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'fredy.martinez@scotiabankcolpatria.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'lufaed123@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'contratacion@ligacancercolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sara.andica@alpopular.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'camilo.gutierrez@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ana.florez@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ingrid.lasprilla@cruzverde.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'abogados@concretodo.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'clgarzon@deloitte.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juridica@tdea.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'paola.hernandez@segurosbolivar.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'biblioteca@tdea.edu.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'msalazar@arrobainversiones.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ivaiethpg49@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'infolegis@aduanasgama.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'paula.herrera@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'aocampo@cfa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'estefania.orrego@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'claudinayin@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'controlinterno@fonaviemcali.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juridico@mct.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sergio.orozco@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'bcrrakro@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jorge.gonzalez@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'maria.olano@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'andrea.barbosa@scotiabankcolpatria.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cneira@alianza.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'frendon@igga.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'carlos.garcia@scotiabankcolpatria.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'panfilomx@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'johannaguerrav@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mauoro@carvajal.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'clargo@cfa.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'gladysgutierrezg@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juanpablo.barrera@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jmuriel@interaseo.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mariailimitada@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sandra.rincon@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ana.erazo@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ignacio.conde@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'guidi082010@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'abogado@jorgeluisquinterogomez.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'diana.cardenas@levapan.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'camilo.rojas@alpopular.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'salvarezm@vid.org.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ifrs@ifas.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'juridica@constructoradeobras.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'ana.saade@invemar.org.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'mari.caceres@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'luis-gomezc@hotmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'laboral@firstcash.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'claudia.perez@invemar.org.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'corrego@funluker.org.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'jennifer.lara@mct.com.co',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'belalcazar@gmail.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sandra.ocampo@stewardcolombia.org',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'saidruby@yahoo.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'cortiz@zfpacifico.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'sergio.zamora@decameron.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'camilo.garcia@crepesywaffles.com',	@Accion  = 1
exec [dbo].[EliminarUsuariosPeruExtrano] @email= 'yenifer.llano@segurosbolivar.com',	@Accion  = 1
